In [86]:

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split # to avoid overfitting
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [87]:
data =pd.read_csv(r'C:\Users\Karthikeyan C\Downloads\heart diseses (1).zip')
data

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1,50,1.0,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,3.0,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0

In [88]:
dataset=data.head(300)
dataset

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1,41,2.0,1,40.0,0.0,0,0,0,310.0,117.5,80.0,26.74,80.0,78.0,0
296,1,51,3.0,0,0.0,0.0,0,0,0,245.0,124.0,69.0,21.52,85.0,68.0,0
297,0,34,3.0,1,10.0,0.0,0,0,0,206.0,101.0,63.0,21.50,75.0,66.0,0
298,1,41,2.0,0,0.0,0.0,0,0,0,173.0,130.0,80.0,28.39,65.0,61.0,0
299,0,62,2.0,0,0.0,1.0,0,1,0,283.0,130.0,80.0,35.20,75.0,83.0,0

In [89]:
X = dataset.drop('TenYearCHD', axis = 1)
X

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1,41,2.0,1,40.0,0.0,0,0,0,310.0,117.5,80.0,26.74,80.0,78.0
296,1,51,3.0,0,0.0,0.0,0,0,0,245.0,124.0,69.0,21.52,85.0,68.0
297,0,34,3.0,1,10.0,0.0,0,0,0,206.0,101.0,63.0,21.50,75.0,66.0
298,1,41,2.0,0,0.0,0.0,0,0,0,173.0,130.0,80.0,28.39,65.0,61.0
299,0,62,2.0,0,0.0,1.0,0,1,0,283.0,130.0,80.0,35.20,75.0,83.0

In [90]:
y = dataset['TenYearCHD']
y

0      0
1      0
2      0
3      1
4      0
      ..
295    0
296    0
297    0
298    0
299    0
Name: TenYearCHD, Length: 300, dtype: int64

In [91]:
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,random_state=1,test_size=0.2)

print('training input sample',Xtrain.shape)
print('training output label',ytrain.shape)

print('testing input sample',Xtest.shape)
print('testing output label',ytest.shape)

training input sample (240, 15)
training output label (240,)
testing input sample (60, 15)
testing output label (60,)

In [92]:
log_reg = LogisticRegression()
log_reg.fit(Xtrain,ytrain)

ypre = log_reg.predict(Xtest)

C:\Users\Karthikeyan C\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [93]:
print('confusion matrix output is\n',confusion_matrix(ytest,ypre))

confusion matrix output is
 [[52  0]
 [ 8  0]]

In [94]:
print('accracy score is:',accuracy_score(ytest,ypre))

accracy score is: 0.8666666666666667

In [95]:
print(classification_report(ytest,ypre))

              precision    recall  f1-score   support

           0       0.87      1.00      0.93        52
           1       0.00      0.00      0.00         8

    accuracy                           0.87        60
   macro avg       0.43      0.50      0.46        60
weighted avg       0.75      0.87      0.80        60

C:\Users\Karthikeyan C\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Karthikeyan C\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Karthikeyan C\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))